# Generated by Django 5.2.1 on 2025-05-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Esfiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simples', 'Simples'), ('tradicional', 'Tradicional'), ('especiais', 'Especiais'), ('premium', 'Premium'), ('doces_gourmet', 'Doces Gourmet')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ingredientes', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='esfihas/')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredientes', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
            ],
        ),
    ]
